"""
Django settings for heritage_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载.env文件
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)
    print(f"✅ 已加载环境变量文件: {env_path}")
else:
    print(f"⚠️  未找到环境变量文件: {env_path}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY 环境变量未设置")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 开发环境允许的主机
ALLOWED_HOSTS = [
    'localhost',  # 本地测试
    '127.0.0.1',  # 本地测试
    '192.168.183.232',  # 局域网IP地址
    '*',  # 允许所有主机访问（开发环境）
]

# CORS设置
# 开发环境CORS设置
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境允许所有来源
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://192.168.183.232",  # 前端通过Nginx访问（80端口）
    "http://localhost:8000",  # 直接访问Django开发服务器
    "http://127.0.0.1:8000",  # 直接访问Django开发服务器
]
# 添加CSRF信任的来源
CSRF_TRUSTED_ORIGINS = [
    "http://192.168.183.232",  # 前端通过Nginx访问（80端口）
    "http://localhost:8000",  # 直接访问Django开发服务器
    "http://127.0.0.1:8000",  # 直接访问Django开发服务器
]

# IP限制配置 - 允许局域网内其他IP访问
# 如果你只想允许特定IP段访问，可以取消注释并修改下面的配置
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.183.232', '192.168.183.*']
# 或者使用IP段表示法
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.183.0/24']

# 百度地图API配置
# 注意：这是浏览器端AK，用于前端JavaScript API调用
# 生产环境中应使用环境变量存储，而不是硬编码在配置文件中
BAIDU_MAP_AK = os.environ.get('BAIDU_MAP_AK')
if not BAIDU_MAP_AK:
    raise ValueError("BAIDU_MAP_AK 环境变量未设置")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # 第三方应用
    "rest_framework",
    "corsheaders",
    
    # 自定义应用
    "heritage_api",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 必须放在最前
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "corsheaders.middleware.CorsMiddleware",  # CORS中间件 - 已移除重复项
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'heritage_project.middleware.IPWhitelistMiddleware',  # IP白名单中间件
]

ROOT_URLCONF = "heritage_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / 'frontend'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "heritage_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get('DB_NAME'),
        "USER": os.environ.get('DB_USER'),
        "PASSWORD": os.environ.get('DB_PASSWORD'),
        "HOST": os.environ.get('DB_HOST', "localhost"),
        "PORT": os.environ.get('DB_PORT', "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        }
    }
}

# 检查必需的数据库配置
if not DATABASES['default']['NAME']:
    raise ValueError("DB_NAME 环境变量未设置")
if not DATABASES['default']['USER']:
    raise ValueError("DB_USER 环境变量未设置")
if not DATABASES['default']['PASSWORD']:
    raise ValueError("DB_PASSWORD 环境变量未设置")
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# 生产环境静态文件收集目录
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 添加 STATICFILES_DIRS 指向前端静态文件目录
STATICFILES_DIRS = [
    BASE_DIR.parent / 'frontend',
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# 媒体文件设置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.qq.com')  # 默认使用QQ邮箱SMTP
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
# 根据端口自动选择加密方式：465端口使用SSL，587端口使用TLS
if EMAIL_PORT == 465:
    EMAIL_USE_SSL = True
    EMAIL_USE_TLS = False
else:
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# 前端URL配置（用于密码重置链接）
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://192.168.183.232')  # 前端通过Nginx访问（80端口）

# 生产环境安全设置
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HTTPS设置（如果使用HTTPS）
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# REST Framework设置
CSRF_COOKIE_HTTPONLY = False # 允许JS读取CSRF cookie
# Django 默认 SESSION_COOKIE_HTTPONLY = True

# SameSite Cookie 设置 (Django 5.x 默认为 'Lax'，显式设置以确保)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
# 对于开发环境 (HTTP)，确保 SECURE 标志为 False (Django 默认)
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Redis配置
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))
REDIS_DB = int(os.environ.get('REDIS_DB', 0))
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', None)  # 如果Redis设置了密码，在这里配置

# Celery配置
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery Beat定时任务配置
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # 每5分钟同步一次浏览量数据
    'sync-view-counts': {
        'task': 'heritage_api.tasks.sync_view_counts_to_db',
        'schedule': crontab(minute='*/5'),  # 每5分钟执行一次
    },
    # 每天凌晨2点清理过期缓存
    'cleanup-cache': {
        'task': 'heritage_api.tasks.cleanup_old_view_count_cache',
        'schedule': crontab(hour=2, minute=0),  # 每天凌晨2点执行
    },
    # 每小时更新搜索索引（如果需要）
    'update-search-index': {
        'task': 'heritage_api.tasks.update_search_index',
        'schedule': crontab(minute=0),  # 每小时执行一次
    },
}

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'heritage.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'heritage_api': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# 上述CORS_ALLOW_ALL_ORIGINS = True 已包含此配置，此处移除
