# Generated by Django 5.2 on 2025-04-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Heritage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("category", models.CharField(max_length=50, verbose_name="类别")),
                ("level", models.CharField(max_length=50, verbose_name="级别")),
                ("region", models.CharField(max_length=50, verbose_name="地区")),
                ("description", models.TextField(verbose_name="描述")),
                ("history", models.TextField(verbose_name="历史")),
                ("lat", models.FloatField(verbose_name="纬度")),
                ("lng", models.FloatField(verbose_name="经度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "非遗项目",
                "verbose_name_plural": "非遗项目",
            },
        ),
        migrations.CreateModel(
            name="HeritageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="heritage_images", verbose_name="图片"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="是否主图"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "heritage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="heritage_api.heritage",
                        verbose_name="非遗项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "非遗项目图片",
                "verbose_name_plural": "非遗项目图片",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, verbose_name="用户ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "heritage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="heritage_api.heritage",
                        verbose_name="非遗项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户收藏",
                "verbose_name_plural": "用户收藏",
                "unique_together": {("user_id", "heritage")},
            },
        ),
    ]
