# Generated by Django 5.2 on 2025-04-30 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heritage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="heritageimage",
            options={},
        ),
        migrations.RemoveField(
            model_name="heritage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="heritage",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="heritage",
            name="level",
        ),
        migrations.RemoveField(
            model_name="heritage",
            name="lng",
        ),
        migrations.RemoveField(
            model_name="heritage",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="heritageimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="heritageimage",
            name="order",
        ),
        migrations.AddField(
            model_name="heritage",
            name="batch",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="heritage",
            name="features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heritage",
            name="gallery_image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="heritage",
            name="inheritors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heritage",
            name="main_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="heritage",
            name="pinyin_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="heritage",
            name="protection_measures",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heritage",
            name="related_works",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heritage",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heritage",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="region",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="heritageimage",
            name="heritage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="heritage_api.heritage",
            ),
        ),
        migrations.AlterField(
            model_name="heritageimage",
            name="image",
            field=models.ImageField(upload_to="heritage_images/"),
        ),
        migrations.AlterField(
            model_name="heritageimage",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="UserCollection",
        ),
    ]
