# Generated by Django 5.2 on 2025-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "heritage_api",
            "0002_alter_heritage_options_alter_heritageimage_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heritage",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="heritage",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="纬度"),
        ),
        migrations.AddField(
            model_name="heritage",
            name="level",
            field=models.CharField(
                blank=True, default="未知级别", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="heritage",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="经度"),
        ),
    ]
