# Generated by Django 4.2.8 on 2025-08-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heritage_api", "0006_userhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "summary",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="摘要"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作者"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="来源"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="来源链接"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="配图链接"
                    ),
                ),
                ("publish_date", models.DateTimeField(verbose_name="发布时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="多个标签用逗号分隔",
                        max_length=200,
                        null=True,
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "非遗资讯",
                "verbose_name_plural": "非遗资讯",
                "ordering": ["-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "summary",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="摘要"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "policy_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="政策文号"
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(max_length=200, verbose_name="发布机构"),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("law", "法律法规"),
                            ("regulation", "部门规章"),
                            ("notice", "通知公告"),
                            ("plan", "规划方案"),
                            ("other", "其他"),
                        ],
                        default="notice",
                        max_length=50,
                        verbose_name="政策类型",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="生效日期"),
                ),
                ("publish_date", models.DateTimeField(verbose_name="发布时间")),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="原文链接"
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="附件链接"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="多个标签用逗号分隔",
                        max_length=200,
                        null=True,
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "相关政策",
                "verbose_name_plural": "相关政策",
                "ordering": ["-publish_date"],
            },
        ),
    ]
