# Generated by Django 4.2.8 on 2025-08-11 07:35

from django.db import migrations


def fix_date_fields(apps, schema_editor):
    """修复Policy模型中的日期字段类型问题"""
    db_alias = schema_editor.connection.alias
    
    # 使用原生SQL来修复日期字段
    with schema_editor.connection.cursor() as cursor:
        # 修复publish_date字段 - 将date类型转换为datetime
        cursor.execute("""
            UPDATE heritage_api_policy 
            SET publish_date = CONCAT(DATE(publish_date), ' 00:00:00')
            WHERE publish_date IS NOT NULL
        """)
        
        # 修复effective_date字段 - 将date类型转换为datetime
        cursor.execute("""
            UPDATE heritage_api_policy 
            SET effective_date = CONCAT(DATE(effective_date), ' 00:00:00')
            WHERE effective_date IS NOT NULL
        """)


def reverse_fix_date_fields(apps, schema_editor):
    """回滚操作"""
    # 不需要回滚操作，因为datetime可以兼容date
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("heritage_api", "0007_news_policy"),
    ]

    operations = [
        migrations.RunPython(fix_date_fields, reverse_fix_date_fields),
    ]
