# Generated by Django 4.2.8 on 2025-08-11 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("heritage_api", "0008_auto_20250811_1535"),
    ]

    operations = []
