# Generated by Django 4.2.8 on 2025-08-11 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("heritage_api", "0009_auto_20250811_1559"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heritage",
            options={
                "ordering": ["id"],
                "verbose_name": "非物质文化遗产",
                "verbose_name_plural": "非物质文化遗产",
            },
        ),
        migrations.AlterModelOptions(
            name="heritageimage",
            options={"verbose_name": "非遗图片", "verbose_name_plural": "非遗图片"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-publish_date"],
                "verbose_name": "新闻资讯",
                "verbose_name_plural": "新闻资讯",
            },
        ),
        migrations.AlterModelOptions(
            name="policy",
            options={
                "ordering": ["-publish_date"],
                "verbose_name": "政策法规",
                "verbose_name_plural": "政策法规",
            },
        ),
        migrations.AlterModelOptions(
            name="userfavorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "用户收藏",
                "verbose_name_plural": "用户收藏",
            },
        ),
        migrations.AlterModelOptions(
            name="userhistory",
            options={
                "ordering": ["-visit_time"],
                "verbose_name": "浏览历史",
                "verbose_name_plural": "浏览历史",
            },
        ),
        migrations.AlterField(
            model_name="heritage",
            name="batch",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="批次"
            ),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="category",
            field=models.CharField(max_length=50, verbose_name="类别"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="description",
            field=models.TextField(verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="features",
            field=models.TextField(blank=True, null=True, verbose_name="基本内容/特征"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="gallery_image_urls",
            field=models.JSONField(blank=True, default=list, verbose_name="图库图片URL列表"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="history",
            field=models.TextField(blank=True, null=True, verbose_name="历史渊源"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="inheritors",
            field=models.TextField(blank=True, null=True, verbose_name="传承人"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="level",
            field=models.CharField(
                blank=True, default="未知级别", max_length=50, null=True, verbose_name="级别"
            ),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="main_image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="主图片URL"
            ),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="项目名称"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="pinyin_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="项目拼音名称"
            ),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="protection_measures",
            field=models.TextField(blank=True, null=True, verbose_name="保护措施"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="region",
            field=models.CharField(max_length=50, verbose_name="地区"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="related_works",
            field=models.TextField(blank=True, null=True, verbose_name="相关制品"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="status",
            field=models.TextField(blank=True, null=True, verbose_name="存续状况"),
        ),
        migrations.AlterField(
            model_name="heritage",
            name="value",
            field=models.TextField(blank=True, null=True, verbose_name="重要价值"),
        ),
        migrations.AlterField(
            model_name="heritageimage",
            name="heritage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="heritage_api.heritage",
                verbose_name="非遗项目",
            ),
        ),
        migrations.AlterField(
            model_name="heritageimage",
            name="image",
            field=models.ImageField(upload_to="heritage_images/", verbose_name="图片"),
        ),
        migrations.AlterField(
            model_name="heritageimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="是否主图"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="issuing_authority",
            field=models.CharField(max_length=100, verbose_name="发布机构"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="policy_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="政策编号"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                choices=[
                    ("law", "法律法规"),
                    ("regulation", "部门规章"),
                    ("notice", "通知公告"),
                    ("standard", "标准规范"),
                    ("guidance", "指导意见"),
                    ("plan", "规划计划"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=20,
                verbose_name="政策类型",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="publish_date",
            field=models.DateField(verbose_name="发布日期"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="来源链接"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="tags",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="标签"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览量"),
        ),
        migrations.AlterField(
            model_name="userfavorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
        ),
        migrations.AlterField(
            model_name="userfavorite",
            name="heritage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="heritage_api.heritage",
                verbose_name="非遗项目",
            ),
        ),
        migrations.AlterField(
            model_name="userfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="heritage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewed_by",
                to="heritage_api.heritage",
                verbose_name="非遗项目",
            ),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="browsing_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="visit_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
        ),
    ]
