# Generated by Django 4.2.8 on 2025-08-28 02:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "heritage_api",
            "0010_alter_heritage_options_alter_heritageimage_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="内容",
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="heritage_api.forumcomment",
                        verbose_name="父评论",
                    ),
                ),
            ],
            options={
                "verbose_name": "论坛评论",
                "verbose_name_plural": "论坛评论",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="内容",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("hidden", "已隐藏"),
                            ("deleted", "已删除"),
                        ],
                        default="published",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False, verbose_name="是否置顶")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否精华"),
                ),
                ("is_locked", models.BooleanField(default=False, verbose_name="是否锁定")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "favorite_count",
                    models.PositiveIntegerField(default=0, verbose_name="收藏数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_reply_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后回复时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "论坛帖子",
                "verbose_name_plural": "论坛帖子",
                "ordering": ["-is_pinned", "-last_reply_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="颜色"
                    ),
                ),
                (
                    "post_count",
                    models.PositiveIntegerField(default=0, verbose_name="帖子数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "论坛标签",
                "verbose_name_plural": "论坛标签",
                "ordering": ["-post_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="ForumUserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_count",
                    models.PositiveIntegerField(default=0, verbose_name="发帖数"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "like_received",
                    models.PositiveIntegerField(default=0, verbose_name="获得点赞数"),
                ),
                (
                    "follower_count",
                    models.PositiveIntegerField(default=0, verbose_name="粉丝数"),
                ),
                (
                    "following_count",
                    models.PositiveIntegerField(default=0, verbose_name="关注数"),
                ),
                ("level", models.PositiveIntegerField(default=1, verbose_name="等级")),
                (
                    "experience",
                    models.PositiveIntegerField(default=0, verbose_name="经验值"),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后活跃时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户论坛统计",
                "verbose_name_plural": "用户论坛统计",
            },
        ),
        migrations.CreateModel(
            name="ForumReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "垃圾信息"),
                            ("inappropriate", "不当内容"),
                            ("harassment", "骚扰"),
                            ("copyright", "版权侵犯"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="举报原因",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="详细描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("handler_note", models.TextField(blank=True, verbose_name="处理备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="举报时间"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="heritage_api.forumcomment",
                        verbose_name="被举报评论",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="heritage_api.forumpost",
                        verbose_name="被举报帖子",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="举报者",
                    ),
                ),
            ],
            options={
                "verbose_name": "举报",
                "verbose_name_plural": "举报",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="forumpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="heritage_api.forumtag",
                verbose_name="标签",
            ),
        ),
        migrations.CreateModel(
            name="ForumCommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="heritage_api.forumcomment",
                        verbose_name="评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论点赞",
                "verbose_name_plural": "评论点赞",
            },
        ),
        migrations.AddField(
            model_name="forumcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="heritage_api.forumpost",
                verbose_name="帖子",
            ),
        ),
        migrations.CreateModel(
            name="ForumAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_pinned", models.BooleanField(default=False, verbose_name="是否置顶")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "论坛公告",
                "verbose_name_plural": "论坛公告",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumUserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关注者",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被关注者",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户关注",
                "verbose_name_plural": "用户关注",
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="ForumPostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="heritage_api.forumpost",
                        verbose_name="帖子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "帖子点赞",
                "verbose_name_plural": "帖子点赞",
                "unique_together": {("user", "post")},
            },
        ),
        migrations.CreateModel(
            name="ForumPostFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="heritage_api.forumpost",
                        verbose_name="帖子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "帖子收藏",
                "verbose_name_plural": "帖子收藏",
                "ordering": ["-created_at"],
                "unique_together": {("user", "post")},
            },
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["-created_at"], name="heritage_ap_created_83946d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["-last_reply_at"], name="heritage_ap_last_re_a082dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["is_pinned", "-last_reply_at"],
                name="heritage_ap_is_pinn_3848a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(fields=["status"], name="heritage_ap_status_af6fb7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="forumcommentlike",
            unique_together={("user", "comment")},
        ),
        migrations.AddIndex(
            model_name="forumcomment",
            index=models.Index(
                fields=["post", "created_at"], name="heritage_ap_post_id_037964_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumcomment",
            index=models.Index(
                fields=["parent"], name="heritage_ap_parent__2949bd_idx"
            ),
        ),
    ]
