# Generated by Django 4.2.7 on 2025-09-13 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "heritage_api",
            "0011_forumcomment_forumpost_forumtag_forumuserstats_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="规划ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="规划标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="规划描述"),
                ),
                ("travel_days", models.PositiveIntegerField(verbose_name="旅游天数")),
                (
                    "departure_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="出发地"
                    ),
                ),
                (
                    "travel_mode",
                    models.CharField(
                        choices=[
                            ("self_drive", "自驾"),
                            ("public_transport", "公共交通"),
                            ("tour_group", "跟团"),
                            ("mixed", "混合"),
                        ],
                        default="self_drive",
                        max_length=20,
                        verbose_name="出行方式",
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[("low", "经济"), ("medium", "中等"), ("high", "豪华")],
                        default="medium",
                        max_length=20,
                        verbose_name="预算范围",
                    ),
                ),
                (
                    "group_size",
                    models.PositiveIntegerField(default=2, verbose_name="团队人数"),
                ),
                (
                    "special_requirements",
                    models.JSONField(blank=True, default=list, verbose_name="特殊要求"),
                ),
                (
                    "contact_info",
                    models.JSONField(blank=True, default=dict, verbose_name="联系信息"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "活跃"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="规划状态",
                    ),
                ),
                (
                    "ai_suggestions",
                    models.JSONField(blank=True, default=dict, verbose_name="AI建议"),
                ),
                (
                    "weather_info",
                    models.JSONField(blank=True, default=dict, verbose_name="天气信息"),
                ),
                (
                    "budget_estimate",
                    models.JSONField(blank=True, default=dict, verbose_name="预算估算"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_edited_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后编辑时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "旅游规划",
                "verbose_name_plural": "旅游规划",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TravelPlanDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(verbose_name="第几天")),
                ("date", models.DateField(blank=True, null=True, verbose_name="日期")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="当日主题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="当日描述"),
                ),
                (
                    "start_location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="起始位置"
                    ),
                ),
                (
                    "end_location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="结束位置"
                    ),
                ),
                (
                    "total_distance",
                    models.FloatField(default=0, verbose_name="总距离(公里)"),
                ),
                (
                    "estimated_travel_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="预估行程时间"
                    ),
                ),
                (
                    "weather_forecast",
                    models.JSONField(blank=True, default=dict, verbose_name="天气预报"),
                ),
                (
                    "daily_tips",
                    models.JSONField(blank=True, default=list, verbose_name="当日建议"),
                ),
                (
                    "estimated_cost",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="当日预估费用"
                    ),
                ),
                (
                    "travel_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_itinerary",
                        to="heritage_api.travelplan",
                        verbose_name="旅游规划",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日行程",
                "verbose_name_plural": "每日行程",
                "ordering": ["day_number"],
                "unique_together": {("travel_plan", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="TravelPlanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("paused", "暂停"),
                            ("completed", "完成"),
                            ("expired", "过期"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="会话状态",
                    ),
                ),
                (
                    "conversation_context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="对话上下文"
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="当前步骤"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="最后活动时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "travel_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_sessions",
                        to="heritage_api.travelplan",
                        verbose_name="旅游规划",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "编辑会话",
                "verbose_name_plural": "编辑会话",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="TravelPlanEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edit_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("modify", "修改"),
                            ("chat_edit", "对话编辑"),
                            ("reset", "重置"),
                            ("apply", "应用"),
                        ],
                        max_length=20,
                        verbose_name="编辑类型",
                    ),
                ),
                ("edit_description", models.TextField(verbose_name="编辑描述")),
                (
                    "user_input",
                    models.TextField(blank=True, null=True, verbose_name="用户输入"),
                ),
                (
                    "ai_response",
                    models.TextField(blank=True, null=True, verbose_name="AI响应"),
                ),
                (
                    "changes_made",
                    models.JSONField(blank=True, default=dict, verbose_name="具体变更"),
                ),
                (
                    "previous_state",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="变更前状态"
                    ),
                ),
                (
                    "new_state",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="变更后状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="编辑时间"),
                ),
                (
                    "travel_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="heritage_api.travelplan",
                        verbose_name="旅游规划",
                    ),
                ),
            ],
            options={
                "verbose_name": "编辑历史",
                "verbose_name_plural": "编辑历史",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TravelPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_order", models.PositiveIntegerField(verbose_name="访问顺序")),
                (
                    "planned_arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="计划到达时间"
                    ),
                ),
                (
                    "planned_departure_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="计划离开时间"
                    ),
                ),
                (
                    "estimated_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="预估游览时长"
                    ),
                ),
                (
                    "transport_from_previous",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="从上一地点的交通信息"
                    ),
                ),
                (
                    "distance_from_previous",
                    models.FloatField(default=0, verbose_name="距离上一地点距离(公里)"),
                ),
                (
                    "visit_notes",
                    models.TextField(blank=True, null=True, verbose_name="游览备注"),
                ),
                (
                    "recommended_activities",
                    models.JSONField(blank=True, default=list, verbose_name="推荐活动"),
                ),
                (
                    "estimated_cost",
                    models.JSONField(blank=True, default=dict, verbose_name="预估费用"),
                ),
                (
                    "is_priority",
                    models.BooleanField(default=False, verbose_name="是否优先项目"),
                ),
                (
                    "user_rating",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="用户评分(1-5)"
                    ),
                ),
                (
                    "heritage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_plans",
                        to="heritage_api.heritage",
                        verbose_name="非遗项目",
                    ),
                ),
                (
                    "travel_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_items",
                        to="heritage_api.travelplanday",
                        verbose_name="所属天数",
                    ),
                ),
                (
                    "travel_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="heritage_api.travelplan",
                        verbose_name="旅游规划",
                    ),
                ),
            ],
            options={
                "verbose_name": "规划项目",
                "verbose_name_plural": "规划项目",
                "ordering": ["travel_day__day_number", "visit_order"],
                "unique_together": {("travel_plan", "heritage")},
            },
        ),
    ]
