# Generated by Django 4.2.7 on 2025-09-29 13:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("heritage_api", "0012_travelplan_travelplanday_travelplansession_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "创作评论",
                "verbose_name_plural": "创作评论",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreationFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
            ],
            options={
                "verbose_name": "创作收藏",
                "verbose_name_plural": "创作收藏",
            },
        ),
        migrations.CreateModel(
            name="CreationLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
            ],
            options={
                "verbose_name": "创作点赞",
                "verbose_name_plural": "创作点赞",
            },
        ),
        migrations.CreateModel(
            name="CreationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("inappropriate", "内容不当"),
                            ("spam", "垃圾信息"),
                            ("copyright", "版权问题"),
                            ("harassment", "骚扰内容"),
                            ("other", "其他问题"),
                        ],
                        max_length=20,
                        verbose_name="举报类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="举报描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("reviewing", "处理中"),
                            ("resolved", "已处理"),
                            ("dismissed", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "evidence_urls",
                    models.JSONField(blank=True, default=list, verbose_name="证据链接"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, null=True, verbose_name="处理结果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="举报时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "创作举报",
                "verbose_name_plural": "创作举报",
            },
        ),
        migrations.CreateModel(
            name="CreationShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("wechat", "微信"),
                            ("weibo", "微博"),
                            ("qq", "QQ"),
                            ("douyin", "抖音"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="分享平台",
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分享时间"),
                ),
            ],
            options={
                "verbose_name": "创作分享",
                "verbose_name_plural": "创作分享",
            },
        ),
        migrations.CreateModel(
            name="CreationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="标签描述"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "创作标签",
                "verbose_name_plural": "创作标签",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="CreationViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, verbose_name="观看时长(秒)"),
                ),
            ],
            options={
                "verbose_name": "创作浏览历史",
                "verbose_name_plural": "创作浏览历史",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCreation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="创作标题")),
                ("description", models.TextField(verbose_name="创作描述")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("video", "视频创作"),
                            ("photo", "图片创作"),
                            ("article", "文章创作"),
                            ("music", "音乐创作"),
                        ],
                        max_length=20,
                        verbose_name="创作类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("reviewing", "审核中"),
                            ("rejected", "已拒绝"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="user_creations/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp3",
                                    "wav",
                                ]
                            )
                        ],
                        verbose_name="媒体文件",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="creation_thumbnails/%Y/%m/%d/",
                        verbose_name="缩略图",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览数"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "share_count",
                    models.PositiveIntegerField(default=0, verbose_name="分享数"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否精选"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="是否公开"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "heritage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creations",
                        to="heritage_api.heritage",
                        verbose_name="关联非遗项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户创作",
                "verbose_name_plural": "用户创作",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="travelplanday",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="travelplanday",
            name="travel_plan",
        ),
        migrations.RemoveField(
            model_name="travelplanedithistory",
            name="travel_plan",
        ),
        migrations.AlterUniqueTogether(
            name="travelplanitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="travelplanitem",
            name="heritage",
        ),
        migrations.RemoveField(
            model_name="travelplanitem",
            name="travel_day",
        ),
        migrations.RemoveField(
            model_name="travelplanitem",
            name="travel_plan",
        ),
        migrations.RemoveField(
            model_name="travelplansession",
            name="travel_plan",
        ),
        migrations.RemoveField(
            model_name="travelplansession",
            name="user",
        ),
        migrations.DeleteModel(
            name="TravelPlan",
        ),
        migrations.DeleteModel(
            name="TravelPlanDay",
        ),
        migrations.DeleteModel(
            name="TravelPlanEditHistory",
        ),
        migrations.DeleteModel(
            name="TravelPlanItem",
        ),
        migrations.DeleteModel(
            name="TravelPlanSession",
        ),
        migrations.AddField(
            model_name="creationviewhistory",
            name="creation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_history",
                to="heritage_api.usercreation",
                verbose_name="创作",
            ),
        ),
        migrations.AddField(
            model_name="creationviewhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creation_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="creationshare",
            name="creation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="heritage_api.usercreation",
                verbose_name="创作",
            ),
        ),
        migrations.AddField(
            model_name="creationshare",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creation_shares",
                to=settings.AUTH_USER_MODEL,
                verbose_name="分享用户",
            ),
        ),
        migrations.AddField(
            model_name="creationreport",
            name="creation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="heritage_api.usercreation",
                verbose_name="被举报创作",
            ),
        ),
        migrations.AddField(
            model_name="creationreport",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AddField(
            model_name="creationreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creation_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="举报人",
            ),
        ),
        migrations.AddField(
            model_name="creationlike",
            name="creation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="heritage_api.usercreation",
                verbose_name="创作",
            ),
        ),
        migrations.AddField(
            model_name="creationlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creation_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="creationfavorite",
            name="creation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="heritage_api.usercreation",
                verbose_name="创作",
            ),
        ),
        migrations.AddField(
            model_name="creationfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creation_favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="creationcomment",
            name="creation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="heritage_api.usercreation",
                verbose_name="创作",
            ),
        ),
        migrations.AddField(
            model_name="creationcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="heritage_api.creationcomment",
                verbose_name="父评论",
            ),
        ),
        migrations.AddField(
            model_name="creationcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creation_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="usercreation",
            index=models.Index(
                fields=["status", "is_public", "created_at"],
                name="heritage_ap_status_3be7e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usercreation",
            index=models.Index(
                fields=["author", "created_at"], name="heritage_ap_author__eb7d21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercreation",
            index=models.Index(
                fields=["heritage", "created_at"], name="heritage_ap_heritag_ecf11e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercreation",
            index=models.Index(
                fields=["type", "created_at"], name="heritage_ap_type_846efa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="creationviewhistory",
            unique_together={("user", "creation")},
        ),
        migrations.AlterUniqueTogether(
            name="creationlike",
            unique_together={("user", "creation")},
        ),
        migrations.AlterUniqueTogether(
            name="creationfavorite",
            unique_together={("user", "creation")},
        ),
    ]
