# Generated by Django 4.2.28 on 2026-03-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_api", "0013_creationcomment_creationfavorite_creationlike_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creationreport",
            name="creation",
        ),
        migrations.RemoveField(
            model_name="creationreport",
            name="handled_by",
        ),
        migrations.RemoveField(
            model_name="creationreport",
            name="reporter",
        ),
        migrations.RemoveField(
            model_name="creationshare",
            name="creation",
        ),
        migrations.RemoveField(
            model_name="creationshare",
            name="user",
        ),
        migrations.DeleteModel(
            name="CreationTag",
        ),
        migrations.RemoveField(
            model_name="forumannouncement",
            name="author",
        ),
        migrations.RemoveField(
            model_name="heritageimage",
            name="heritage",
        ),
        migrations.DeleteModel(
            name="CreationReport",
        ),
        migrations.DeleteModel(
            name="CreationShare",
        ),
        migrations.DeleteModel(
            name="ForumAnnouncement",
        ),
        migrations.DeleteModel(
            name="HeritageImage",
        ),
    ]
