# Generated by Django 4.2.28 on 2026-03-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_api", "0014_remove_creationreport_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="标记为精选资讯，将在首页精选区展示",
                verbose_name="是否精选",
            ),
        ),
    ]
