# Generated by Django 4.2.28 on 2026-03-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_api", "0016_add_forum_announcement_and_rule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumrule",
            name="title",
        ),
        migrations.AlterField(
            model_name="forumrule",
            name="content",
            field=models.CharField(
                help_text="简短的规则描述，如：尊重他人，文明讨论",
                max_length=200,
                verbose_name="规则内容",
            ),
        ),
    ]
