# Generated by Django 4.2.7 on 2026-05-12 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("heritage_api", "0017_simplify_forum_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("login", "登录"),
                            ("logout", "登出"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(max_length=50, verbose_name="资源类型"),
                ),
                (
                    "resource_id",
                    models.IntegerField(blank=True, null=True, verbose_name="资源ID"),
                ),
                (
                    "resource_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="资源名称"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="操作详情"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理操作日志",
                "verbose_name_plural": "管理操作日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="heritage_ap_created_cc9838_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="heritage_ap_resourc_484510_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="heritage_ap_user_id_53323b_idx",
                    ),
                ],
            },
        ),
    ]
